# Generated by Django 4.1.5 on 2023-01-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('NumeroLegajo', models.IntegerField()),
                ('NumeroDocumento', models.IntegerField(primary_key=True, serialize=False)),
                ('Cargo', models.CharField(max_length=20)),
            ],
        ),
    ]
